/**
 * lib/seedDemo.ts — DEMO DATA ONLY.
 *
 * ⚠️  None of the data produced by this module represents real
 * financial records. Every number is generated by a deterministic
 * seeded random walk + a few hand-tuned spikes. This module is the
 * single source of demo data for the WalletSync frontend; running it
 * never touches a real wallet, a real account, or a real customer.
 *
 * Used by:
 *   - scripts/seed-demo-data.mjs (CLI)
 *   - POST /api/persona/switch (in-app dropdown)
 *
 * Both call into the same `seedDemo(persona, days)` so the shape and
 * values are identical regardless of which path produced the data.
 *
 * Personas: freelancer | small_business | student
 *   See PERSONAS below for the per-persona baseline, volatility,
 *   drift, and spike cadence.
 */

import Database from "better-sqlite3";
import { randomUUID } from "node:crypto";
import path from "node:path";
import fs from "node:fs";

import { PROVIDERS, type Provider } from "@/features/wallet/types";

/* ─── public types ─────────────────────────────────────────────────── */

import type { PersonaDisplay, PersonaName } from "./metaTypes";
export type { PersonaName, MetaSnapshot } from "./metaTypes";

export interface PersonaSpec {
  name: PersonaName;
  label: string;
  description: string;
  baseline: Record<Provider, number>;
  /** Per-day random jitter (BDT, +/-). */
  volatility: Record<Provider, number>;
  /** Per-day drift toward cash-out (negative) or cash-in (positive). */
  drift: Record<Provider, number>;
  /** Probability that any given day is a "payday" / large inflow day. */
  spikeChance: number;
  spikeRange: [number, number];
  /** Which providers receive the spike bump on a payday day. */
  spikeProviders: Provider[];
}

export interface SeedResult {
  persona: PersonaName;
  label: string;
  description: string;
  generatedAt: string;
  totalEntries: number;
  daysCovered: number;
  perProvider: Record<Provider, number>;
  dbPath: string;
}

/* ─── personas ─────────────────────────────────────────────────────── */

export const PERSONA_SEEDS: Record<PersonaName, PersonaSpec> = {
  freelancer: {
    name: "freelancer",
    label: "Freelancer",
    description:
      "Mixed inflows from freelance projects, steady daily outflows. " +
      "Rocket used as the savings stash.",
    baseline: { bkash: 8500, nagad: 4200, rocket: 24000 },
    volatility: { bkash: 600, nagad: 350, rocket: 900 },
    drift: { bkash: -120, nagad: -80, rocket: 80 },
    spikeChance: 0.13,
    spikeRange: [3500, 9000],
    spikeProviders: ["bkash", "rocket"],
  },
  small_business: {
    name: "small_business",
    label: "Small Business (Retail)",
    description:
      "High daily turn-over on bKash and Nagad from customer " +
      "transactions. Rocket held back for supplier payments.",
    baseline: { bkash: 18000, nagad: 12500, rocket: 9500 },
    volatility: { bkash: 1800, nagad: 1500, rocket: 400 },
    drift: { bkash: -250, nagad: -180, rocket: 60 },
    spikeChance: 0.22,
    spikeRange: [8000, 22000],
    spikeProviders: ["bkash", "nagad"],
  },
  student: {
    name: "student",
    label: "Student",
    description:
      "Low magnitudes, frequent small changes from daily expenses. " +
      "Rocket used least; mostly sits empty.",
    baseline: { bkash: 1800, nagad: 950, rocket: 350 },
    volatility: { bkash: 220, nagad: 140, rocket: 60 },
    drift: { bkash: -30, nagad: -15, rocket: 5 },
    spikeChance: 0.05,
    spikeRange: [1500, 3500],
    spikeProviders: ["bkash"],
  },
};

/** Display-only metadata shared with the client. Re-export the
 *  PersonaDisplay map so existing consumers that imported PERSONAS
 *  from seedDemo keep working on the server side. */
export const PERSONAS = (() => {
  const out: Record<PersonaName, PersonaDisplay> = {} as never;
  for (const name of Object.keys(PERSONA_SEEDS) as PersonaName[]) {
    out[name] = {
      name,
      label: PERSONA_SEEDS[name].label,
      description: PERSONA_SEEDS[name].description,
    };
  }
  return out;
})();

/* ─── deterministic seeded PRNG ────────────────────────────────────── */

function hashSeed(str: string): number {
  let h = 2166136261;
  for (let i = 0; i < str.length; i++) {
    h ^= str.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function uniform(rand: () => number, min: number, max: number): number {
  return min + (max - min) * rand();
}

function pick<T>(rand: () => number, arr: readonly T[]): T {
  return arr[Math.floor(rand() * arr.length)] as T;
}

/* ─── generation ───────────────────────────────────────────────────── */

interface SeededEntry {
  id: string;
  provider: Provider;
  balance: number;
  timestamp: string;
}

function generateEntries(
  config: PersonaSpec,
  days: number,
  now: number,
): SeededEntry[] {
  const out: SeededEntry[] = [];
  const balance: Record<Provider, number> = { ...config.baseline };
  const rand = mulberry32(hashSeed(`walletsync-demo:${config.name}`));

  for (let d = days - 1; d >= 0; d--) {
    const dayTimestamp = now - d * 24 * 60 * 60 * 1000;
    const dayDate = new Date(dayTimestamp);

    // Payday/spike day? Skip day 0 so the "now" entry isn't a spike
    // (we want the user's most recent balance to look like a normal
    // edit, not a just-arrived payday).
    const isSpikeDay =
      d !== 0 && rand() < config.spikeChance && d % 2 === 0;
    const spikeProvider = isSpikeDay ? pick(rand, config.spikeProviders) : null;
    const spikeAmount = isSpikeDay
      ? uniform(rand, config.spikeRange[0], config.spikeRange[1])
      : 0;
    const baseCount = isSpikeDay ? 2 : 1;
    const extraCount = isSpikeDay && rand() < 0.4 ? 2 : 0;
    const entryCount = baseCount + extraCount;

    for (let e = 0; e < entryCount; e++) {
      // Pull the balance toward the persona baseline + apply daily drift
      // + random jitter, per provider.
      for (const provider of PROVIDERS) {
        const pullToBaseline =
          (config.baseline[provider] - balance[provider]) * 0.04;
        const jitter = uniform(
          rand,
          -config.volatility[provider],
          config.volatility[provider],
        );
        const drift = config.drift[provider] + pullToBaseline + jitter;
        balance[provider] = Math.max(0, balance[provider] + drift);
      }

      // If this is a payday day + this provider + the first entry of
      // the day, bump the balance by the spike amount.
      if (
        isSpikeDay &&
        spikeProvider !== null &&
        e === 0
      ) {
        balance[spikeProvider] += spikeAmount;
      }

      // Lay the entry down across the day. First entry at ~09:00,
      // extras later. Last entry's timestamp clamped to `now`.
      const hour = Math.min(
        23,
        9 + Math.floor((24 / (entryCount + 1)) * (e + 1)),
      );
      const ts = new Date(dayDate);
      ts.setHours(hour, Math.floor(rand() * 60), 0, 0);
      const isoTs =
        ts.getTime() > now ? new Date(now).toISOString() : ts.toISOString();

      for (const provider of PROVIDERS) {
        out.push({
          id: randomUUID(),
          provider,
          balance: Math.round(balance[provider] * 100) / 100,
          timestamp: isoTs,
        });
      }
    }
  }

  return out;
}

/* ─── schema + persistence ─────────────────────────────────────────── */

function ensureDir(p: string): void {
  const d = path.dirname(p);
  if (!fs.existsSync(d)) fs.mkdirSync(d, { recursive: true });
}

function openDb(dbPath: string): Database.Database {
  ensureDir(dbPath);
  const db = new Database(dbPath);
  db.pragma("journal_mode = WAL");
  db.pragma("foreign_keys = ON");
  db.exec(`
    CREATE TABLE IF NOT EXISTS balance_entries (
      id        TEXT PRIMARY KEY,
      provider  TEXT NOT NULL CHECK (provider IN ('bkash','nagad','rocket')),
      balance   REAL NOT NULL CHECK (balance >= 0),
      timestamp TEXT NOT NULL
    );
    CREATE INDEX IF NOT EXISTS idx_balance_entries_provider_ts
      ON balance_entries (provider, timestamp DESC);

    CREATE TABLE IF NOT EXISTS meta (
      key   TEXT PRIMARY KEY,
      value TEXT NOT NULL
    );
  `);
  return db;
}

/**
 * Run the seed against the database at `dbPath`. Wipes existing entries
 * + meta rows, then inserts the freshly-generated series + persona
 * metadata, all inside a single transaction.
 */
export function seedDemo(
  personaName: PersonaName,
  days: number,
  dbPath: string,
  now: number = Date.now(),
): SeedResult {
  if (!(personaName in PERSONA_SEEDS)) {
    throw new Error(
      `Unknown persona: "${personaName}". Valid: ${Object.keys(PERSONA_SEEDS).join(", ")}`,
    );
  }
  if (!Number.isFinite(days) || days < 30 || days > 180) {
    throw new Error(`days must be between 30 and 180 (got ${days}).`);
  }
  const config = PERSONA_SEEDS[personaName];
  const entries = generateEntries(config, days, now);

  const db = openDb(dbPath);
  const generatedAt = new Date(now).toISOString();
  try {
    const wipeEntries = db.prepare("DELETE FROM balance_entries");
    const wipeMeta = db.prepare("DELETE FROM meta");
    const insert = db.prepare(
      "INSERT INTO balance_entries (id, provider, balance, timestamp) VALUES (?, ?, ?, ?)",
    );
    const insertMeta = db.prepare(
      "INSERT INTO meta (key, value) VALUES (?, ?)",
    );

    const tx = db.transaction((rows: SeededEntry[]) => {
      wipeEntries.run();
      wipeMeta.run();
      for (const r of rows) {
        insert.run(r.id, r.provider, r.balance, r.timestamp);
      }
      insertMeta.run("seed.persona", config.name);
      insertMeta.run("seed.label", config.label);
      insertMeta.run("seed.description", config.description);
      insertMeta.run("seed.generated_at", generatedAt);
      insertMeta.run("seed.demo", "true");
    });
    tx(entries);
  } finally {
    db.close();
  }

  // Compute summary stats.
  const perProvider = { bkash: 0, nagad: 0, rocket: 0 } as Record<
    Provider,
    number
  >;
  const daySet = new Set<string>();
  for (const e of entries) {
    perProvider[e.provider]++;
    daySet.add(e.timestamp.slice(0, 10));
  }

  return {
    persona: config.name,
    label: config.label,
    description: config.description,
    generatedAt,
    totalEntries: entries.length,
    daysCovered: daySet.size,
    perProvider,
    dbPath,
  };
}

/* ─── meta read helpers ────────────────────────────────────────────── */

export function readMeta(dbPath: string): import("./metaTypes").MetaSnapshot {
  const db = new Database(dbPath, { readonly: true });
  try {
    const rows = db
      .prepare("SELECT key, value FROM meta")
      .all() as Array<{ key: string; value: string }>;
    const map = new Map(rows.map((r) => [r.key, r.value]));
    const personaRaw = map.get("seed.persona");
    const persona =
      personaRaw && personaRaw in PERSONAS
        ? (personaRaw as PersonaName)
        : null;
    return {
      isDemo: map.get("seed.demo") === "true",
      persona,
      label: map.get("seed.label") ?? null,
      description: map.get("seed.description") ?? null,
      generatedAt: map.get("seed.generated_at") ?? null,
    };
  } finally {
    db.close();
  }
}

/* ─── by-day aggregator (for sparkline) ────────────────────────────── */

// The aggregator now lives in lib/sparklineSeries.ts (pure module, no
// node:* / better-sqlite3 deps) so client components can import it.
// Re-export here for backwards compat — the seed CLI and any future
// server-side consumer keep working without changing their import.
export {
  buildDailySeries,
  type DailyPoint,
  type ProviderSeries,
} from "./sparklineSeries";