/**
 * lib/seedDemo.ts — DEMO DATA ONLY.
 *
 * ⚠️  None of the data produced by this module represents real
 * financial records. Every number is generated by a deterministic
 * seeded random walk + a few hand-tuned spikes. This module is the
 * single source of demo data for the WalletSync frontend; running it
 * never touches a real wallet, a real account, or a real customer.
 *
 * Used by:
 *   - scripts/seed-demo-data.mjs (CLI)
 *   - POST /api/persona/switch (in-app dropdown)
 *
 * Both call into the same `seedDemo(persona, days, db)` so the shape and
 * values are identical regardless of which path produced the data.
 *
 * Personas: freelancer | small_business | student
 *   See PERSONAS below for the per-persona baseline, volatility,
 *   drift, and spike cadence.
 *
 * Phase 4: writes to the v2 schema (personas + provider_balance +
 * per-persona balance_entries + meta). The caller hands us an open
 * `Database` so the migration runner in `lib/infrastructure/migrate.ts`
 * has already provisioned the schema; we only write rows.
 */

import path from "node:path";
import fs from "node:fs";
import Database from "better-sqlite3";

import { migrate } from "@/lib/infrastructure/migrate";
import { PROVIDERS, type Provider } from "@/features/wallet/types";
import { bdtToPaise } from "@/lib/domain/money";

type DB = InstanceType<typeof Database>;

const MIGRATIONS_DIR = path.resolve(
  process.cwd(),
  "src",
  "lib",
  "infrastructure",
  "migrations",
);

/* ─── public types ─────────────────────────────────────────────────── */

import type { PersonaDisplay, PersonaName } from "./metaTypes";
export type { PersonaName, MetaSnapshot } from "./metaTypes";

export interface PersonaSpec {
  name: PersonaName;
  label: string;
  description: string;
  baseline: Record<Provider, number>;
  /** Per-day random jitter (+/-), in the account's currency. */
  volatility: Record<Provider, number>;
  /** Per-day drift toward cash-out (negative) or cash-in (positive). */
  drift: Record<Provider, number>;
  /** Probability that any given day is a "payday" / large inflow day. */
  spikeChance: number;
  spikeRange: [number, number];
  /** Which providers receive the spike bump on a payday day. */
  spikeProviders: Provider[];
  /** Per-provider currency. Defaults to 'BDT' when absent. */
  currency?: Partial<Record<Provider, 'BDT' | 'USD'>>;
  /** USD→BDT exchange rate used for USD entries. Ignored for BDT. */
  usdExchangeRate?: number;
}

export interface SeedResult {
  persona: PersonaName;
  label: string;
  description: string;
  generatedAt: string;
  totalEntries: number;
  daysCovered: number;
  perProvider: Record<Provider, number>;
  dbPath: string;
}

/* ─── personas ─────────────────────────────────────────────────────── */

export const PERSONA_SEEDS: Record<PersonaName, PersonaSpec> = {
  freelancer: {
    name: "freelancer",
    label: "Freelancer",
    description:
      "Mixed inflows from freelance projects, steady daily outflows. " +
      "bKash receives USD payments. Rocket used as the savings stash.",
    baseline: { bkash: 8500, nagad: 4200, rocket: 24000 },
    volatility: { bkash: 600, nagad: 350, rocket: 900 },
    drift: { bkash: -120, nagad: -80, rocket: 80 },
    spikeChance: 0.13,
    spikeRange: [3500, 9000],
    spikeProviders: ["bkash", "rocket"],
    // bKash receives USD freelance payments; Nagad and Rocket stay BDT.
    currency: { bkash: "USD" },
    usdExchangeRate: 110,
  },
  small_business: {
    name: "small_business",
    label: "Small Business (Retail)",
    description:
      "High daily turn-over on bKash and Nagad from customer " +
      "transactions. Rocket held back for supplier payments.",
    baseline: { bkash: 18000, nagad: 12500, rocket: 9500 },
    volatility: { bkash: 1800, nagad: 1500, rocket: 400 },
    drift: { bkash: -250, nagad: -180, rocket: 60 },
    spikeChance: 0.22,
    spikeRange: [8000, 22000],
    spikeProviders: ["bkash", "nagad"],
  },
  student: {
    name: "student",
    label: "Student",
    description:
      "Low magnitudes, frequent small changes from daily expenses. " +
      "Rocket used least; mostly sits empty.",
    baseline: { bkash: 1800, nagad: 950, rocket: 350 },
    volatility: { bkash: 220, nagad: 140, rocket: 60 },
    drift: { bkash: -30, nagad: -15, rocket: 5 },
    spikeChance: 0.05,
    spikeRange: [1500, 3500],
    spikeProviders: ["bkash"],
  },
};

/** Display-only metadata shared with the client. Re-export the
 *  PersonaDisplay map so existing consumers that imported PERSONAS
 *  from seedDemo keep working on the server side. */
export const PERSONAS = (() => {
  const out: Record<PersonaName, PersonaDisplay> = {} as never;
  for (const name of Object.keys(PERSONA_SEEDS) as PersonaName[]) {
    out[name] = {
      name,
      label: PERSONA_SEEDS[name].label,
      description: PERSONA_SEEDS[name].description,
    };
  }
  return out;
})();

/* ─── deterministic seeded PRNG ────────────────────────────────────── */

function hashSeed(str: string): number {
  let h = 2166136261;
  for (let i = 0; i < str.length; i++) {
    h ^= str.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function uniform(rand: () => number, min: number, max: number): number {
  return min + (max - min) * rand();
}

function pick<T>(rand: () => number, arr: readonly T[]): T {
  return arr[Math.floor(rand() * arr.length)] as T;
}

/* ─── generation ───────────────────────────────────────────────────── */

interface SeededEntry {
  provider: Provider;
  balance: number;
  timestamp: number;
  /** Currency of this entry. Omitted means BDT. */
  currency?: 'BDT' | 'USD';
  /** USD→BDT exchange rate at entry time. Non-null only for USD entries. */
  exchangeRate?: number | null;
}

function generateEntries(
  config: PersonaSpec,
  days: number,
  now: number,
): SeededEntry[] {
  const out: SeededEntry[] = [];
  const balance: Record<Provider, number> = { ...config.baseline };
  const rand = mulberry32(hashSeed(`walletsync-demo:${config.name}`));

  // Determine per-provider currency (default BDT).
  const currencyConfig: Record<Provider, 'BDT' | 'USD'> = {
    bkash: config.currency?.bkash ?? 'BDT',
    nagad: config.currency?.nagad ?? 'BDT',
    rocket: config.currency?.rocket ?? 'BDT',
  };

  for (let d = days - 1; d >= 0; d--) {
    const dayTimestamp = now - d * 24 * 60 * 60 * 1000;
    const dayDate = new Date(dayTimestamp);

    const isSpikeDay =
      d !== 0 && rand() < config.spikeChance && d % 2 === 0;
    const spikeProvider = isSpikeDay ? pick(rand, config.spikeProviders) : null;
    const spikeAmount = isSpikeDay
      ? uniform(rand, config.spikeRange[0], config.spikeRange[1])
      : 0;
    const baseCount = isSpikeDay ? 2 : 1;
    const extraCount = isSpikeDay && rand() < 0.4 ? 2 : 0;
    const entryCount = baseCount + extraCount;

    for (let e = 0; e < entryCount; e++) {
      for (const provider of PROVIDERS) {
        const pullToBaseline =
          (config.baseline[provider] - balance[provider]) * 0.04;
        const jitter = uniform(
          rand,
          -config.volatility[provider],
          config.volatility[provider],
        );
        const drift = config.drift[provider] + pullToBaseline + jitter;
        balance[provider] = Math.max(0, balance[provider] + drift);
      }

      if (isSpikeDay && spikeProvider !== null && e === 0) {
        balance[spikeProvider] += spikeAmount;
      }

      const hour = Math.min(
        23,
        9 + Math.floor((24 / (entryCount + 1)) * (e + 1)),
      );
      const ts = new Date(dayDate);
      ts.setHours(hour, Math.floor(rand() * 60), 0, 0);
      const epochMs = Math.min(ts.getTime(), now);

      for (const provider of PROVIDERS) {
        const entryCurrency = currencyConfig[provider];
        const entry: SeededEntry = {
          provider,
          balance: Math.round(balance[provider] * 100) / 100,
          timestamp: epochMs,
        };
        if (entryCurrency === 'USD') {
          entry.currency = 'USD';
          entry.exchangeRate = config.usdExchangeRate ?? 110;
        }
        out.push(entry);
      }
    }
  }

  return out;
}

/* ─── schema + persistence ─────────────────────────────────────────── */

/** Open a writable `Database` for the seeder. Caller-owned lifecycle
 *  (we open + close so the CLI doesn't leak file handles). */
function openDb(dbPath: string): DB {
  const dir = path.dirname(dbPath);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  const db = new Database(dbPath);
  db.pragma("journal_mode = WAL");
  db.pragma("foreign_keys = ON");
  return db;
}

/**
 * Run the seed against the database at `dbPath`. Wipes any prior
 * balance_entries for the target persona, then writes the freshly
 * generated series + persona metadata + provider_balance rows, all
 * inside a single transaction. The schema itself is provisioned
 * idempotently by the migration runner.
 */
export function seedDemo(
  personaName: PersonaName,
  days: number,
  dbPath: string,
  now: number = Date.now(),
): SeedResult {
  if (!(personaName in PERSONA_SEEDS)) {
    throw new Error(
      `Unknown persona: "${personaName}". Valid: ${Object.keys(PERSONA_SEEDS).join(", ")}`,
    );
  }
  if (!Number.isFinite(days) || days < 30 || days > 180) {
    throw new Error(`days must be between 30 and 180 (got ${days}).`);
  }
  const config = PERSONA_SEEDS[personaName];
  const entries = generateEntries(config, days, now);

  const db = openDb(dbPath);
  const generatedAt = new Date(now).toISOString();
  try {
    // Provision schema (no-op on a previously-migrated DB).
    migrate(db, MIGRATIONS_DIR);

    // Prepare statements once; reuse inside the transaction.
    const upsertPersona = db.prepare(
      `INSERT INTO personas
         (id, display_name, opening_bkash, opening_nagad, opening_rocket,
          inflow_rate, volatility)
       VALUES (?, ?, ?, ?, ?, 1.0, 0.10)
       ON CONFLICT(id) DO UPDATE SET
         display_name   = excluded.display_name,
         opening_bkash  = excluded.opening_bkash,
         opening_nagad  = excluded.opening_nagad,
         opening_rocket = excluded.opening_rocket`,
    );
    const wipeEntries = db.prepare(
      "DELETE FROM balance_entries WHERE persona_id = ?",
    );
    const upsertBalance = db.prepare(
      `INSERT INTO provider_balance
         (persona_id, provider_id, balance, version_id, updated_at)
       VALUES (?, ?, ?, 1, ?)
       ON CONFLICT(persona_id, provider_id) DO UPDATE SET
         balance    = excluded.balance,
         version_id = provider_balance.version_id + 1,
         updated_at = excluded.updated_at`,
    );
    const insertEntry = db.prepare(
      `INSERT INTO balance_entries
         (persona_id, provider_id, balance, source, transfer_id, ts,
          currency, exchange_rate)
       VALUES (?, ?, ?, 'seed', NULL, ?, ?, ?)`,
    );
    const upsertMeta = db.prepare(
      "INSERT INTO meta (key, value) VALUES (?, ?) " +
        "ON CONFLICT(key) DO UPDATE SET value = excluded.value",
    );

    const tx = db.transaction(() => {
      // 1. Persona row (id matches the persona name).
      //    The opening_* columns are typed paise; convert from BDT
      //    (which is what `config.baseline` carries) to paise here.
      upsertPersona.run(
        config.name,
        config.label,
        bdtToPaise(config.baseline.bkash),
        bdtToPaise(config.baseline.nagad),
        bdtToPaise(config.baseline.rocket),
      );

      // 2. Wipe any prior entries for this persona only.
      wipeEntries.run(config.name);

      // 3. Current balances: the most-recent entry's balance, or the
      //    baseline if none.
      const lastByProvider: Record<Provider, number> = { ...config.baseline };
      for (let i = entries.length - 1; i >= 0; i--) {
        const e = entries[i]!;
        // entries are grouped by day then provider, newest-first; the
        // last one we see for each provider is the newest.
        if (lastByProvider[e.provider] === config.baseline[e.provider]) {
          lastByProvider[e.provider] = e.balance;
        }
      }
      // 4. Reset provider_balance to the current snapshot.
      //    `provider_balance.balance` and `balance_entries.balance` are
      //    typed INTEGER paise; `lastByProvider[p]` and `e.balance` are
      //    in BDT here, so convert before writing.
      const t = Date.now();
      for (const p of PROVIDERS) {
        upsertBalance.run(
          config.name,
          p,
          bdtToPaise(lastByProvider[p] as number),
          t,
        );
      }

      // 5. Insert the history rows.
      for (const e of entries) {
        const entryCurrency = e.currency ?? 'BDT';
        const entryRate = entryCurrency === 'USD' && e.exchangeRate != null
          ? e.exchangeRate
          : null;
        insertEntry.run(
          config.name,
          e.provider,
          bdtToPaise(e.balance),
          e.timestamp,
          entryCurrency,
          entryRate,
        );
      }

      // 6. Demo metadata + active_persona marker so the entries repo
      //    scopes its queries to this persona.
      upsertMeta.run("seed.persona", config.name);
      upsertMeta.run("seed.label", config.label);
      upsertMeta.run("seed.description", config.description);
      upsertMeta.run("seed.generated_at", generatedAt);
      upsertMeta.run("seed.demo", "true");
      upsertMeta.run("active_persona", config.name);
    });
    tx();
  } finally {
    db.close();
  }

  // Compute summary stats.
  const perProvider = { bkash: 0, nagad: 0, rocket: 0 } as Record<
    Provider,
    number
  >;
  const daySet = new Set<string>();
  for (const e of entries) {
    perProvider[e.provider]++;
    daySet.add(new Date(e.timestamp).toISOString().slice(0, 10));
  }

  return {
    persona: config.name,
    label: config.label,
    description: config.description,
    generatedAt,
    totalEntries: entries.length,
    daysCovered: daySet.size,
    perProvider,
    dbPath,
  };
}

/* ─── meta read helpers ────────────────────────────────────────────── */

export function readMeta(dbPath: string): import("./metaTypes").MetaSnapshot {
  const db = new Database(dbPath, { readonly: true });
  try {
    const rows = db
      .prepare("SELECT key, value FROM meta")
      .all() as Array<{ key: string; value: string }>;
    const map = new Map(rows.map((r) => [r.key, r.value]));
    const personaRaw = map.get("seed.persona");
    const persona =
      personaRaw && personaRaw in PERSONAS
        ? (personaRaw as PersonaName)
        : null;
    return {
      isDemo: map.get("seed.demo") === "true",
      persona,
      label: map.get("seed.label") ?? null,
      description: map.get("seed.description") ?? null,
      generatedAt: map.get("seed.generated_at") ?? null,
    };
  } finally {
    db.close();
  }
}

/* ─── by-day aggregator (for sparkline) ────────────────────────────── */

// The aggregator now lives in lib/sparklineSeries.ts (pure module, no
// node:* / better-sqlite3 deps) so client components can import it.
// Re-export here for backwards compat — the seed CLI and any future
// server-side consumer keep working without changing their import.
export {
  buildDailySeries,
  type DailyPoint,
  type ProviderSeries,
} from "./sparklineSeries";